---
- hosts: all
  become: yes
  pre_tasks:
    - name: Dist Upgrade Server
      apt: upgrade=dist update_cache=yes
  roles:
    - axelitus.common
    - axelitus.mysql
    - axelitus.php
    - axelitus.composer
    - axelitus.nginx